name: Build & upload to Firebase App Distribution 

on: 
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:


  build:

    name: Building and distributing app
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Add secret
        run: echo ${{secrets.FIREBASE_KEY}} | base64 -d > see-joy-3f334-ef61a3aeac47.json

      - name: build release 
        run: ./gradlew assembleRelease

      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: 1:826001615661:android:e75bc039e6e313c89d01a4
          serviceCredentialsFile: see-joy-3f334-ef61a3aeac47.json
          groups: testers
          file: build/app/outputs/apk/release/app-release.apk
    